function init(self)
	-- Create Memory for wasmer
	local wasm_memory, err = wasmer.memory.new {
		minimum = 10, -- 640kB
		--maximum = 100
	}

	print (tostring(wasm_memory)  .. " " .. #wasm_memory)
	print (wasm_memory.grow)
	wasm_memory:grow(1)
	wasm_memory:write(8, "asdf")
	print(wasm_memory[8])

	bytes = sys.load_resource("/data/test.wasm")

	local modules = {
		env = { memory = wasm_memory }
	}
	
	wasmer.import (bytes, modules)
end
